### ISSUE TITLE
Remove a single word from default bad words

### ISSUE THREAD

**Issue by endel** [seiyria/censor-sensor#2]
Hi @seiyria :)

Is it possible to remove a single word from the default words file? I'd like to remove `hell`, for example. 

Cheers! Thanks!

**Comment by seiyria** [comment]
Hey! It looks like that isn't currently possible, but I can get a change in to make it work momentarily with `removeWord`.

**Comment by endel** [comment]
That'd be nice! I've tried doing this but apparently it only removes from the user-defined list :)

**Comment by seiyria** [comment]
This should be functional in `1.0.6`. Let me know if you need anything else!

**Comment by endel** [comment]
Wow that was fast! Thanks a lot!! 🎉
